name             'capistrano-static'
maintainer       'Adam Krone'
maintainer_email 'krone.adam@gmail.com'
license          'apachev2'
description      'Installs/Configures a system for capistrano static site deployment'
long_description 'Installs/Configures a system for capistrano static site deployment'
version          '0.2.0'

depends 'apt'
depends 'users'
depends 'sudo'
depends 'ssh-hardening'
depends 'apache2'
